apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "batchchar-pipeline"
  annotations:
    scenarios.ai.sap.com/description: "Train regression + classification models to predict paper batch defects"
    scenarios.ai.sap.com/name: "Batchchar Defect Prediction"
    executables.ai.sap.com/name: "batchchar-intransit-predict"
    artifacts.ai.sap.com/batcharpredictdata.kind: "dataset"
    artifacts.ai.sap.com/batcharpredictmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "batchchar-pipeline"
    ai.sap.com/version: '2.0'
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: mypipeline
  arguments:
    parameters: []
  templates:
    - name: mypipeline
      steps:
        - - name: mytrainer
            template: mycodeblock1

    - name: mycodeblock1
      inputs:
        artifacts:
          - name: batcharpredictdata
            path: /app/data/final_synthetic_paper_batch_data_with_defects.csv
      outputs:
        artifacts:
          - name: batcharpredictmodel
            globalName: batch_char_predict_model
            path: /app/model/model.tar.gz
            archive:
              none: {}
      container:
        image: docker.io/pareshkolte/batchar_prediction:01
        command: ["/bin/sh", "-c"]
        args:
          - "mkdir -p /app/model && python /app/src/main.py"
