apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: batch-char-data-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Predict final batch characteristics and defect likelihood"
    scenarios.ai.sap.com/name: "Batch characteristic prediction"
    executables.ai.sap.com/description: "Training pipeline for batch characteristic prediction"
    executables.ai.sap.com/name: "training-batchchar"
    artifacts.ai.sap.com/batchcharpredictdata.kind:  "dataset"
    artifacts.ai.sap.com/batchcharpredictmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "batch-char-data-pipeline"
    ai.sap.com/version: '2.0'
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: mypipeline
  arguments:
    parameters: []
  templates:
  - name: mypipeline
    steps:
    - - name: mytrainer
        template: mycodeblock1
  - name: mycodeblock1
    inputs:
      artifacts:
        - name: batcharpredictdata
          path: /app/data/
    outputs:
      artifacts:
        - name: batchpredictmodel
          globalName: batch_char_model
          path: /app/model/model.tar.gz
          archive:
            none: 
              {}
    container:
      image: docker.io/pareshkolte/batch-char-prediction:01
      command: ["/bin/sh", "-c"]
      env: []
      args:
        - "python /app/src/main.py"
    
