apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: batchchar-intransit-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Train regression + classification models to predict paper batch defects"
    scenarios.ai.sap.com/name: "Batchchar Defect Prediction"
    executables.ai.sap.com/name: "batchchar-intransit-predict"
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        artifacts:
          - name: paper_batch_data
            path: /app/data/final_synthetic_paper_batch_data_with_defects.csv
      outputs:
        artifacts:
          - name: trained_models
            path: /app/model/
      container:
        image: docker.io/pareshkolte/batchar_prediction:01
        command: ["python"]
        args: ["main.py"]
